### ISSUE TITLE
Group Paths by Tag

### ISSUE THREAD

**Issue by atomfrede** [atomfrede/generator-jhipster-swagger2markup#1]
Hi,

the generated HTML/PDF looks better, if you group the paths by tags/resources.

The Gradle script should look like this:

```
convertSwagger2markup {
    dependsOn test
    inputDir swaggerOutputDir
    examplesDir asciiDocOutputDir
    pathsGroupedBy io.github.robwin.swagger2markup.GroupBy.TAGS
}
```

The HTML/PDF output looks like this then.

https://github.com/Swagger2Markup/swagger2markup/blob/master/images/Swagger2Markup.PNG

submitted by @RobWin

**Comment by RobWin** [comment]
Sry. Hatte das falsche Repo erwischt.

**Comment by atomfrede** [comment]
:) Kein Problem
