### ISSUE TITLE
Add changelog html file

### ISSUE THREAD

**Issue by moifort** [atomfrede/generator-jhipster-swagger2markup#17]
I propose to add a asciidoc changelog for a JHipster application. 
- It will be an option in the module
- It will automatically put the generated html in the angularJs application during war packing
- It will be accessible by http://my-jhipster-app.com/#/changelog

What do you think? if you like the idea I can make a PR.

**Comment by atomfrede** [comment]
Yes I like it. Maybe we could also put the generated api doc into the war file.

**Comment by moifort** [comment]
Yes, we did it on my current project too. I will try to make a PR soon!
