### ISSUE TITLE
Documentation for Microservices

### ISSUE THREAD

**Issue by pascalgrimaud** [atomfrede/generator-jhipster-swagger2markup#20]
Hi Frederik,

I wanted to create the documentation for my (experimental) project: 
https://github.com/pascalgrimaud/jhipster-microservices

I just gave a very fast try:
- I'm not sure your module is up-to-date -> some missing artifacts
- it seems your module isn't intended to work with Microservices or maybe I'm wrong?

```
[ERROR] Failed to execute goal on project micro: Could not resolve dependencies for project io.github.pascalgrimaud:micro:war:0.0.1-SNAPSHOT: Could not find artifact io.github.swagger2markup:swagger2markup-spring-restdocs-ext:jar:1.1.0 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

I just wanted to notice you, so no worry if you don't have time to have a look ;-)
If I manage to make it works for Microservices, I will fix it

**Comment by atomfrede** [comment]
Hi Pascal,

Yes, I didn't try it with microservices and I already thought it might not work :). But in fact that artifact looks strange, as rest docs should not be under ``io.github.swagger2markup``. Will have a quick look at the maven, maybe some copy and paste mistake.

**Comment by pascalgrimaud** [comment]
Oh no, the version 1.1.0 is me who try to change it, because it failed for 1.0.0 too :D
Bad copy/paste from me

**Comment by pascalgrimaud** [comment]
Closing this, as it's open for too long.
And with JHipster 5, if some people need this, this module need to be reworked entirely
