### ISSUE TITLE
The wiki is not cleaaaaaaar!! 

### ISSUE THREAD

**Issue by shmersy** [atomfrede/generator-jhipster-swagger2markup#21]
- there nothing anywhere that say to add jcenter repo :s
- no demo, no example no youtube demo...I'm frustrated
- I followed the tutorial I have issues : 

INFO] --- asciidoctor-maven-plugin:1.5.3:process-asciidoc (output-html) @ GUI ---
io/console not supported; tty will not be manipulated
asciidoctor: WARNING: overview/workflow.adoc: line 40: no callouts refer to list item 1
asciidoctor: WARNING: overview/workflow.adoc: line 42: no callouts refer to list item 2
asciidoctor: WARNING: index.adoc: line 5: include file not found: C:/Users/a644583/git/MooseSpirit1/MOOSeSpirit/GUI/target/docs/asciidoc/paths.adoc
asciidoctor: WARNING: index.adoc: line 6: include file not found: C:/Users/a644583/git/MooseSpirit1/MOOSeSpirit/GUI/target/docs/asciidoc/definitions.adoc

-Do I need to run tests to generate the docs and pdf????? can you write more phrases if you don't want I'll write it for you

**Comment by pascalgrimaud** [comment]
You should go to the real wiki from the official project:
- http://asciidoctor.org/docs/asciidoctor-maven-plugin/
- https://github.com/asciidoctor/asciidoctor

This project is simply a module, to integrate the official asciidoctor.

And please remember we are doing this for free in our free time.

**Comment by atomfrede** [comment]
Thanks @pascalgrimaud 

Btw, looking at the readme you'll find

> The html or pdf generation is bound to the install lifecycle phase. The swagger2markup creation is not bound to any phase, therefore you must create it explicitly during the test phase and process the swagger file:

    mvnw test swagger2markup:convertSwagger2markup install

So for me its quite clear what to execute. If you are using jhipster 4 there might be sime issues as I did not update the module yet. I will try to update it as soon as possible, but my time is limited, so if you would like to test it and maybe provide a pull request for things not working please go ahead.
