### ISSUE TITLE
swagger2markup-maven-plugin:1.0.1:convertSwagger2markup (default-cli) 

### ISSUE THREAD

**Issue by shmersy** [atomfrede/generator-jhipster-swagger2markup#22]
Failed to execute goal 'convertSwagger2markup': swaggerPath does not exist: C:\...\target\swagger\swagger.json 

Please help.

**Comment by atomfrede** [comment]
Sorry, without any further information you won't get any help.

**Comment by soyoeml** [comment]
[ERROR] Failed to execute goal io.github.swagger2markup:swagger2markup-maven-plugin:1.3.1:convertSwagger2markup (default-cli) on project http-2-proxy: Failed to execute goal 'convertSwagger2markup': swaggerPath does not exist: /home/jhipster/app/target/swagger/swagger.json -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by atomfrede** [comment]
Without e.g. jhipster version, configuration this is not helpful , sorry. But again the swagger file is not present that's why it fails.

**Comment by ibarbalho** [comment]
> Failed to execute goal 'convertSwagger2markup': swaggerPath does not exist: C:...\target\swagger\swagger.json
> 
> Please help.

Did you get this problem solved?
