### ISSUE TITLE
Install dependencies

### ISSUE THREAD

**Issue by pascalgrimaud** [atomfrede/generator-jhipster-swagger2markup#3]
Simple question :
https://github.com/atomfrede/generator-jhipster-swagger2markup/blob/master/generators/app/index.js#L173-L175

Is it usefull ? It seems you just added gradle dependencies. Maybe it can save time ?
In my docker module, I remove it because I don't need to npm install / bower install

cc @moifort : same question for your modules too ;)

=> I'm not sure, that's why it's a question !

**Comment by moifort** [comment]
If you don't want to make  npm install / bower install / wiredep (like me) or other command to execute after instilling dependency. I think is not useful for you.

In my case I use it, because all my module add new bower package for angular and I need to install it. I execute wiredep after, like below:

``` javascript
install: function () {
        var injectDependenciesAndConstants = function () {
            switch (this.frontendBuilder) {
                case 'gulp':
                    this.spawnCommand('gulp', ['ngconstant:dev', 'wiredep:test', 'wiredep:app']);
                    break;
                case 'grunt':
                default:
                    this.spawnCommand('grunt', ['ngconstant:dev', 'wiredep']);
            }
        };

        this.installDependencies({
                callback: injectDependenciesAndConstants.bind(this)
            }
        );
    }
```

**Comment by atomfrede** [comment]
@pascalgrimaud Thanks for the hint. I guess you're right, I don't need it, will fix it soon.
