### ISSUE TITLE
Add Asciidoc sample

### ISSUE THREAD

**Issue by moifort** [atomfrede/generator-jhipster-swagger2markup#5]
I discover recently Asciidoc and how much it's awesome!

I want to make a PR with a sample of how we can generate doc with Asciidoc:
- Add new question if user want a doc sample
- Add sample doc with Lorem Ipsum text, with basic code sample, warning, note, title, subtitle etc.

What do you think?

**Comment by atomfrede** [comment]
Pull requests are welcome of course. I left it out first but of course adding  an example chapter before the endpoint documentation is very helpful.

**Comment by moifort** [comment]
Cool :+1:
